//go:build !ignore_autogenerated

// Code generated by controller-gen normally lives here - hand-written for
// now until we wire up `make generate`.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ResourceDelta) DeepCopyInto(out *ResourceDelta) {
	*out = *in
	if in.CurrentRequests != nil {
		out.CurrentRequests = in.CurrentRequests.DeepCopy()
	}
	if in.ProposedRequests != nil {
		out.ProposedRequests = in.ProposedRequests.DeepCopy()
	}
}

func (in *ResourceDelta) DeepCopy() *ResourceDelta {
	if in == nil {
		return nil
	}
	out := new(ResourceDelta)
	in.DeepCopyInto(out)
	return out
}

func (in *HomeostatRecommendationSpec) DeepCopyInto(out *HomeostatRecommendationSpec) {
	*out = *in
	out.Target = in.Target
	if in.ResourceDeltas != nil {
		out.ResourceDeltas = make([]ResourceDelta, len(in.ResourceDeltas))
		for i := range in.ResourceDeltas {
			in.ResourceDeltas[i].DeepCopyInto(&out.ResourceDeltas[i])
		}
	}
	if in.RequiresLabels != nil {
		out.RequiresLabels = make(map[string]string, len(in.RequiresLabels))
		for k, v := range in.RequiresLabels {
			out.RequiresLabels[k] = v
		}
	}
}

func (in *HomeostatRecommendationStatus) DeepCopyInto(out *HomeostatRecommendationStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *HomeostatRecommendation) DeepCopyInto(out *HomeostatRecommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HomeostatRecommendation) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(HomeostatRecommendation)
	in.DeepCopyInto(out)
	return out
}

func (in *HomeostatRecommendationList) DeepCopyInto(out *HomeostatRecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]HomeostatRecommendation, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *HomeostatRecommendationList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(HomeostatRecommendationList)
	in.DeepCopyInto(out)
	return out
}
